version: "3.8"
services:
    symfony:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/website
        ports:
            - 80:80
        environment:
            APP_ENV: 'dev'